language: scala
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - npm
before-script:
  - jdk_switcher use oraclejdk8
  - sbt coreJS/fullOptJS
  - ./make_node_module 2.12
  - (cd ./node && npm update)
script:
  - sbt test
  - (cd ./node && npm test)
