language: scala
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq oracle-java8-installer oracle-java8-set-default npm
  - sudo npm install -g n
before_script:
  - jdk_switcher use oraclejdk8
  - sbt coreJS/fullOptJS
  - ./make_node_module 2.12
  - (cd ./node && npm update)
script:
  - sbt test
  - (cd ./node && npm test)
